enable_ssl: True
handle_cookie: True

host:
  self: google-mirror-nangua.now.sh
  proxy: s2-us2.startpage.com

replaced_urls:
  - old: www.startpage.com
    new: s2-us2.startpage.com
  - old: s2-us2.startpage.com
    new: google-mirror-nangua.now.sh
